version: "3.3"
services:
  client:
    build: ./time-tracking-client
    ports:
     - 5000:5000
    environment:
      - REACT_APP_API_PATH=localhost:8080
  rest:
    build: ./time-tracking-rest
    ports:
     - 8080:8080
    environment:
     - spring_datasource_url=jdbc:postgresql://database:5432/time_tracking
  database:
    image: postgres:9.4
    environment:
      POSTGRES_DB: time_tracking
      POSTGRES_USER: postgres