version: "3.3"
services:
  rest:
    build: ./time-tracking-rest
    ports:
     - 8080:8080
    environment:
      - spring_datasource_url=jdbc:postgresql://database:5432/time_tracking
  database:
    image: postgres:9.4
    environment:
      POSTGRES_DB: time_tracking
      POSTGRES_USER: postgres